url: https://eddyli.dev
baseurl: /

# Site settings
title: Eddy Li
email: li.edwa@northeastern.edu
description: "Hi, I'm Eddy Li, Software Engineer"

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fakeedwardli?lang=en
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/NEUDitao
  - title: linkedin
    url: https://www.linkedin.com/in/eddy-li/

# Postal address (add as many lines as necessary)
address:
  - line: 23348 Augusta
  - line: Mission Viejo, CA 92692

# Build settings
markdown: kramdown
permalink: pretty
