remote_theme: daattali/beautiful-jekyll@6.0.1

title: Eddy Li 
author: Eddy Li

navbar-links:
  Work Experience: "work-experience"
  Blog: "blog"
  Personal:
    - Race Results: "personal/race-results"
    - Music: "personal/music"
  Contact: "contact"
  Resume: "resume.pdf"

avatar: "https://avatars.githubusercontent.com/u/33675688?v=4"

social-network-links:
  email: "edward.d.li@gmail.com"
  github: "NEUDitao"
  linkedin: "eddy-li"


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme

favicons:
  16: 'assets/kaine.jpg'

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#8FDC81"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#8FDC81"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

commentbox: "5763276415696896-proj"